import type { Metadata } from "next";
import "./globals.css";
import HomeLayoutWrapper from "@/wrapper/HomeLayoutWrapper";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HomeLayoutWrapper>{children}</HomeLayoutWrapper>
        <Toaster richColors />
      </body>
    </html>
  );
}
